version: '3'

services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
